In [2]:
import numpy as np

The Basics

In [7]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [12]:
b = np.array([[4.0,5.0,6.1],[7.2,8.3,9.5]])
print(b)

[[4.  5.  6.1]
 [7.2 8.3 9.5]]


In [4]:
# Get Dimension
b.ndim

2

In [5]:
# Get Shape
b.shape

(2, 3)

In [8]:
# Get Type
a.dtype

dtype('int16')

In [9]:
# Item size
a.itemsize

2

In [10]:
# Get total size
a.size * a.itemsize

6

In [15]:
# Get total size
b.nbytes

48