Accessing/Changing specific elements, rows columns

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# accessing the first row's 4th element
a[0,3]

4

In [5]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get specific column
a[:,2]

print()
for i in range(0,7):
    print(a[:,i])


In [12]:
# [row  ,start index : end index : step size]
a[1, 2:5:1]

array([10, 11, 12])

In [13]:
# Change specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [14]:
a[:,2] = [1,5]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [16]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element (work outside in)
b[:,1:]

array([[[3, 4]],

       [[7, 8]]])

In [21]:
# Replacing
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
