Accessing/Changing specific elements, rows columns

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# accessing the first row's 4th element
a[0,3]

4

In [5]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])