In [1]:
import numpy as np

In [2]:
# ALL zero 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
# ALL ones 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])