In [1]:
import numpy as np

In [2]:
# ALL zero 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
# ALL ones 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# Any other number
np.full((2,2), 1, dtype='float32')

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [9]:
#  Random decimial number
np.random.rand(4,2)

array([[0.23914407, 0.30321135],
       [0.59719798, 0.97731777],
       [0.6695634 , 0.61777315],
       [0.80192486, 0.43729437]])

In [10]:
# random int 
np.random.randint(7, size=(3,3))

array([[0, 6, 5],
       [4, 1, 4],
       [5, 2, 6]])

In [11]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]
