Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [10]:
b = np.array([0.5, 1., 1.5, 2.])
print(b)
print(a + b)


[0.5 1.  1.5 2. ]
[1.5 3.  4.5 6. ]


In [11]:
a ** 2

array([ 1,  4,  9, 16])