Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [10]:
b = np.array([0.5, 1., 1.5, 2.])
print(b)
print(a + b)


[0.5 1.  1.5 2. ]
[1.5 3.  4.5 6. ]


In [11]:
a ** 2

array([ 1,  4,  9, 16])

In [12]:
# take in sine / cosine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [15]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 5)
print(b)


print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[15. 15.]
 [15. 15.]]


In [16]:
# Find te determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [20]:
stats = np.array([[1,2,3],[4,5,-5]])
stats

array([[ 1,  2,  3],
       [ 4,  5, -5]])

In [22]:
np.min(stats, axis=1)

array([ 1,  2, -5])

In [24]:
np.max(stats, axis=0)

array([4, 5, 3])

In [26]:
# Sum based on column values
np.sum(stats,axis=0)

array([ 5,  7, -2])